# Generated by Django 6.0.3 on 2026-04-18 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaminationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#FF0000', max_length=7)),
            ],
            options={
                'db_table': 'contamination_types',
            },
        ),
        migrations.CreateModel(
            name='WaterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='water_images/%Y/%m/')),
                ('water_source', models.CharField(choices=[('tap', 'Tap water'), ('borewell', 'Borewell'), ('river', 'River/Lake'), ('tanker', 'Water tanker'), ('well', 'Open well'), ('other', 'Other')], max_length=20)),
                ('water_color', models.CharField(choices=[('clear', 'Clear'), ('yellow', 'Yellow/Brown'), ('green', 'Green'), ('black', 'Black'), ('white', 'Milky White'), ('other', 'Other')], max_length=20)),
                ('water_smell', models.CharField(choices=[('none', 'No smell'), ('chlorine', 'Chlorine/Chemical'), ('sulfur', 'Rotten Egg / Sulfur'), ('sewage', 'Sewage'), ('musty', 'Musty/Earthy'), ('other', 'Other')], max_length=20)),
                ('turbidity_score', models.IntegerField(default=1, help_text='1=Clear, 5=Very murky')),
                ('symptoms_diarrhea', models.BooleanField(default=False)),
                ('symptoms_vomiting', models.BooleanField(default=False)),
                ('symptoms_skin_rash', models.BooleanField(default=False)),
                ('symptoms_fever', models.BooleanField(default=False)),
                ('symptoms_none', models.BooleanField(default=True)),
                ('ph_value', models.FloatField(blank=True, null=True)),
                ('tds_value', models.FloatField(blank=True, help_text='Total Dissolved Solids ppm', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'water_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
